### ISSUE TITLE
Missing awe plugins

### ISSUE THREAD

**Issue by squio** [ezartech/ezar-poi#1]
The Awe.js environment fails to initialize because of missing required plugins.

Adding the following (from the awe.js distribution) fixes this:

    www/libs/awe.js/js/plugins/
		StereoEffect.js
		VREffect.js
		awe-standard-object_clicked.js
		awe-standard-object_clicked_or_focused.js
		awe-standard-object_focused.js
		awe.gyro.js
		awe.mouse.js
		awe.rendering_effects.js

**Comment by wayneparrott** [comment]
Thanks for identifying this issue. The .gitignore was a little to aggressive at filtering out dirs named plugin/
Fixed.

**Comment by ezartech** [comment]
Fixed.
